openapi: 3.0.3
info:
  title: Receipt Upload API
  version: 1.0.0
  description: API contract for uploading receipt images and triggering OCR processing

paths:
  /api/v1/upload:
    post:
      summary: Upload receipt image for OCR processing
      operationId: uploadReceipt
      tags:
        - Receipt Processing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  format: binary
                  description: Receipt image file (JPG or PNG, max 5MB)
      responses:
        '200':
          description: Receipt uploaded successfully and OCR processing initiated
          content:
            application/json:
              schema:
                type: object
                required:
                  - receipt_id
                  - status
                  - extracted_data
                properties:
                  receipt_id:
                    type: string
                    format: uuid
                    example: "a3bb189e-8bf9-3888-9912-ace4e6543002"
                  status:
                    type: string
                    enum: [completed, failed]
                    example: "completed"
                  extracted_data:
                    type: object
                    nullable: true
                    properties:
                      transaction_date:
                        type: string
                        format: date
                        nullable: true
                        example: "2025-09-28"
                      transaction_date_confidence:
                        type: number
                        format: float
                        minimum: 0.0
                        maximum: 1.0
                        example: 0.92
                      items:
                        type: string
                        nullable: true
                        maxLength: 500
                        example: "Coffee; Sandwich; Water"
                      items_confidence:
                        type: number
                        format: float
                        minimum: 0.0
                        maximum: 1.0
                        example: 0.85
                      total_amount:
                        type: number
                        format: decimal
                        nullable: true
                        example: 24.50
                      total_amount_confidence:
                        type: number
                        format: float
                        minimum: 0.0
                        maximum: 1.0
                        example: 0.95
                  processing_time_ms:
                    type: integer
                    description: OCR processing duration in milliseconds
                    example: 3200
        '400':
          description: Invalid request (file too large, wrong format, or missing)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                fileTooLarge:
                  value:
                    error_code: "FILE_TOO_LARGE"
                    message: "File size exceeds 5MB limit"
                invalidFormat:
                  value:
                    error_code: "INVALID_FORMAT"
                    message: "Only JPG and PNG formats are supported"
                missingFile:
                  value:
                    error_code: "MISSING_FILE"
                    message: "No file provided in request"
        '500':
          description: Server error during OCR processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                ocrFailed:
                  value:
                    error_code: "OCR_FAILED"
                    message: "Unable to process image"

components:
  schemas:
    Error:
      type: object
      required:
        - error_code
        - message
      properties:
        error_code:
          type: string
          example: "FILE_TOO_LARGE"
        message:
          type: string
          example: "File size exceeds 5MB limit"
